### ISSUE TITLE
"Helper text" in the "add evidence form" appears to be incorrect

### ISSUE THREAD

**Issue by zlskidmore** [genome/civic-client#357]
When submitting an evidence item the helper text under evidence level appears to be incorrect for evidence level C and D

for example evidence level C - case study says "In vivo or in vitro models support association" shouldn't this be "individual case reports from clinical journals"

**Comment by malachig** [comment]
Good eye @zlskidmore we recently changed the order of C and D.  Looks like this help text got missed.  We need to update this in three places in the code:

```
app/views/add/evidence/addEvidenceBasic.js,
app/views/events/evidence/edit/evidenceEditBasic.js',
components/services/ConfigService.js',
```

**Comment by kkrysiak** [comment]
Fixed in these 3 locations with d4722b2

**Comment by zlskidmore** [comment]
@kkrysiak I  noticed that this is not yet fixed, has this just not been pushed to the civic live site yet?

**Comment by kkrysiak** [comment]
It probably hasn't been pushed to the live yet. We have a deploy planned for today I do believe so stay tuned!

**Comment by malachig** [comment]
To me it seems to be fixed in the add evidence and edit evidence forms. @zlskidmore , can you check again and confirm?

**Comment by zlskidmore** [comment]
Yes, this is fixed, I neglected to clear the cache earlier
